#!/usr/bin/env python3
"""Generate the Codeforces card shown in the profile README."""

from __future__ import annotations

import html
import json
import os
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo


HANDLE = os.environ.get("CF_HANDLE", "T_CrB")
OUTPUT = Path(__file__).resolve().parents[1] / "assets" / "codeforces-stats.svg"


def api_call(path: str, **query: str | int) -> dict:
    url = "https://codeforces.com/api/" + path + "?" + urllib.parse.urlencode(query)
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "T-CrB-profile-readme/1.0"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.load(response)
    if payload.get("status") != "OK":
        raise RuntimeError(f"Codeforces API error: {payload}")
    return payload


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def latest_accepted_submissions() -> list[dict]:
    # Codeforces returns submissions newest-first.
    submissions = api_call(
        "user.status", handle=HANDLE, **{"from": 1}, count=100
    )["result"]
    return [item for item in submissions if item.get("verdict") == "OK"][:5]


def format_points(problem: dict) -> str:
    points = problem.get("points")
    if points is None:
        return "—"
    return f"{points:g}" if isinstance(points, float) else str(points)


def format_submission(submission: dict) -> tuple[str, str, str, str]:
    problem = submission.get("problem", {})
    contest_id = problem.get("contestId")
    index = problem.get("index", "")
    name = str(problem.get("name", "Unknown problem"))
    label = f"{contest_id}{index} · {name}" if contest_id else name
    # Keep long problem names inside the card while retaining the full name in
    # the link target.
    if len(label) > 52:
        label = label[:49] + "…"

    if contest_id:
        link = (
            f"https://codeforces.com/contest/{contest_id}/problem/"
            f"{urllib.parse.quote(str(index))}"
        )
    else:
        link = "https://codeforces.com/profile/" + urllib.parse.quote(HANDLE)

    timestamp = submission.get("creationTimeSeconds")
    if timestamp:
        local_time = datetime.fromtimestamp(
            timestamp, timezone.utc
        ).astimezone(ZoneInfo("Asia/Shanghai"))
        when = local_time.strftime("%Y-%m-%d %H:%M")
    else:
        when = "Recently"
    return label, format_points(problem), when, link


def build_rows(submissions: list[dict]) -> str:
    rows: list[str] = []
    for number, submission in enumerate(submissions, start=1):
        problem, points, when, link = format_submission(submission)
        y = 170 + (number - 1) * 30
        rows.append(
            f'''  <text x="30" y="{y}" class="muted">{number:02d}</text>
  <a href="{esc(link)}"><text x="75" y="{y}" class="value" textLength="470" lengthAdjust="spacingAndGlyphs">{esc(problem)}</text></a>
  <text x="590" y="{y}" class="points">{esc(points)}</text>
  <text x="665" y="{y}" class="muted">{esc(when)}</text>'''
        )

    if not rows:
        rows.append('  <text x="75" y="170" class="value">No accepted submissions found</text>')
    return "\n".join(rows)


def build_svg(user: dict, submissions: list[dict]) -> str:
    rating = user.get("rating", "Unrated")
    max_rating = user.get("maxRating", "—")
    rank = str(user.get("rank", "unrated")).replace("_", " ").title()
    profile_link = "https://codeforces.com/profile/" + urllib.parse.quote(HANDLE)
    updated = datetime.now(timezone.utc).astimezone(ZoneInfo("Asia/Shanghai"))
    updated_text = updated.strftime("%Y-%m-%d %H:%M UTC+8")

    return f'''<!-- Generated by scripts/update_codeforces.py. Do not edit manually. -->
<svg xmlns="http://www.w3.org/2000/svg" width="820" height="365" viewBox="0 0 820 365" role="img" aria-labelledby="title desc">
  <title id="title">Codeforces statistics for {esc(HANDLE)}</title>
  <desc id="desc">Current rating {esc(rating)} and the five latest accepted submissions</desc>
  <rect width="820" height="365" rx="10" fill="#1a1b26"/>
  <rect width="820" height="6" rx="3" fill="#1f8acb"/>
  <style>
    .title {{ fill: #70a5fd; font: 700 25px 'Segoe UI', Arial, sans-serif; }}
    .label {{ fill: #38c2b0; font: 600 14px 'Segoe UI', Arial, sans-serif; }}
    .value {{ fill: #f0f6fc; font: 600 15px 'Segoe UI', Arial, sans-serif; }}
    .points {{ fill: #f6c177; font: 700 15px 'Segoe UI', Arial, sans-serif; }}
    .muted {{ fill: #8b949e; font: 13px 'Segoe UI', Arial, sans-serif; }}
    .accent {{ fill: #bf91f3; font: 700 28px 'Segoe UI', Arial, sans-serif; }}
  </style>
  <a href="{esc(profile_link)}"><text x="30" y="45" class="title">Codeforces · {esc(HANDLE)}</text></a>
  <text x="30" y="78" class="label">Current Rating</text>
  <text x="30" y="110" class="accent">{esc(rating)}</text>
  <text x="170" y="78" class="label">Max Rating</text>
  <text x="170" y="110" class="value">{esc(max_rating)}</text>
  <text x="320" y="78" class="label">Rank</text>
  <text x="320" y="110" class="value">{esc(rank)}</text>
  <line x1="30" y1="130" x2="790" y2="130" stroke="#30363d"/>
  <text x="30" y="155" class="label">Latest Accepted Submissions</text>
  <text x="590" y="155" class="label">Points</text>
  <text x="665" y="155" class="label">Time (UTC+8)</text>
{build_rows(submissions)}
  <text x="30" y="340" class="muted">Last refreshed: {esc(updated_text)}</text>
</svg>
'''


def main() -> None:
    user = api_call("user.info", handles=HANDLE)["result"][0]
    submissions = latest_accepted_submissions()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build_svg(user, submissions), encoding="utf-8")
    print(f"Updated {OUTPUT} for {HANDLE} ({len(submissions)} ACs)")


if __name__ == "__main__":
    main()
