#!/usr/bin/env python3
"""Generate the Codeforces card shown in the profile README."""

from __future__ import annotations

import html
import json
import os
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo


HANDLE = os.environ.get("CF_HANDLE", "T_CrB")
OUTPUT = Path(__file__).resolve().parents[1] / "assets" / "codeforces-stats.svg"


def api_call(path: str, **query: str | int) -> dict:
    url = "https://codeforces.com/api/" + path + "?" + urllib.parse.urlencode(query)
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "T-CrB-profile-readme/1.0"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.load(response)
    if payload.get("status") != "OK":
        raise RuntimeError(f"Codeforces API error: {payload}")
    return payload


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def latest_accepted_submission() -> dict | None:
    # The endpoint is newest-first. One hundred submissions keeps scheduled
    # API requests small while covering the usual case.
    submissions = api_call("user.status", handle=HANDLE, **{"from": 1}, count=100)["result"]
    return next((item for item in submissions if item.get("verdict") == "OK"), None)


def submission_text(submission: dict | None) -> tuple[str, str, str]:
    if not submission:
        return "No accepted submission found", "", ""

    problem = submission.get("problem", {})
    contest_id = problem.get("contestId")
    index = problem.get("index", "")
    name = problem.get("name", "Unknown problem")
    label = f"{contest_id}{index} · {name}" if contest_id else name
    if contest_id:
        link = f"https://codeforces.com/contest/{contest_id}/problem/{urllib.parse.quote(str(index))}"
    else:
        link = "https://codeforces.com/profile/" + urllib.parse.quote(HANDLE)

    timestamp = submission.get("creationTimeSeconds")
    if timestamp:
        local_time = datetime.fromtimestamp(
            timestamp, timezone.utc
        ).astimezone(ZoneInfo("Asia/Shanghai"))
        when = local_time.strftime("%Y-%m-%d %H:%M CST")
    else:
        when = "Recently"
    return label, when, link


def build_svg(user: dict, submission: dict | None) -> str:
    rating = user.get("rating", "Unrated")
    max_rating = user.get("maxRating", "—")
    rank = user.get("rank", "unrated").replace("_", " ")
    problem, when, problem_link = submission_text(submission)
    profile_link = "https://codeforces.com/profile/" + urllib.parse.quote(HANDLE)
    updated = datetime.now(timezone.utc).astimezone(ZoneInfo("Asia/Shanghai"))
    updated_text = updated.strftime("%Y-%m-%d %H:%M CST")

    problem_anchor = (
        f'<a href="{esc(problem_link)}"><text x="390" y="167" class="value">{esc(problem)}</text></a>'
        if problem_link
        else f'<text x="390" y="167" class="value">{esc(problem)}</text>'
    )

    return f'''<!-- Generated by scripts/update_codeforces.py. Do not edit manually. -->
<svg xmlns="http://www.w3.org/2000/svg" width="760" height="250" viewBox="0 0 760 250" role="img" aria-labelledby="title desc">
  <title id="title">Codeforces statistics for {esc(HANDLE)}</title>
  <desc id="desc">Current rating {esc(rating)} and latest accepted submission {esc(problem)}</desc>
  <rect width="760" height="250" rx="10" fill="#1a1b26"/>
  <rect width="760" height="6" rx="3" fill="#1f8acb"/>
  <style>
    .title {{ fill: #70a5fd; font: 700 25px 'Segoe UI', Arial, sans-serif; }}
    .label {{ fill: #38c2b0; font: 600 15px 'Segoe UI', Arial, sans-serif; }}
    .value {{ fill: #f0f6fc; font: 600 16px 'Segoe UI', Arial, sans-serif; }}
    .muted {{ fill: #8b949e; font: 13px 'Segoe UI', Arial, sans-serif; }}
    .accent {{ fill: #bf91f3; font: 700 28px 'Segoe UI', Arial, sans-serif; }}
  </style>
  <a href="{esc(profile_link)}"><text x="30" y="45" class="title">Codeforces · {esc(HANDLE)}</text></a>
  <text x="30" y="86" class="label">Current Rating</text>
  <text x="30" y="120" class="accent">{esc(rating)}</text>
  <text x="150" y="86" class="label">Max Rating</text>
  <text x="150" y="120" class="value">{esc(max_rating)}</text>
  <text x="270" y="86" class="label">Rank</text>
  <text x="270" y="120" class="value">{esc(rank.title())}</text>
  <line x1="30" y1="143" x2="730" y2="143" stroke="#30363d"/>
  <text x="30" y="172" class="label">Latest AC</text>
  {problem_anchor}
  <text x="390" y="198" class="muted">{esc(when)}</text>
  <text x="30" y="225" class="muted">Last refreshed: {esc(updated_text)}</text>
</svg>
'''


def main() -> None:
    user = api_call("user.info", handles=HANDLE)["result"][0]
    submission = latest_accepted_submission()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build_svg(user, submission), encoding="utf-8")
    print(f"Updated {OUTPUT} for {HANDLE}")


if __name__ == "__main__":
    main()
